package com.xv.org.templating2;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Templating2DO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Templating2DO() {
    }

}