package com.xv.org.templating2;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Templating2DO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer creditScore;
   private java.lang.String creditStatus;

   private java.lang.String borrowerName;

   public Templating2DO()
   {
   }

   public java.lang.Integer getCreditScore()
   {
      return this.creditScore;
   }

   public void setCreditScore(java.lang.Integer creditScore)
   {
      this.creditScore = creditScore;
   }

   public java.lang.String getCreditStatus()
   {
      return this.creditStatus;
   }

   public void setCreditStatus(java.lang.String creditStatus)
   {
      this.creditStatus = creditStatus;
   }

   public java.lang.String getBorrowerName()
   {
      return this.borrowerName;
   }

   public void setBorrowerName(java.lang.String borrowerName)
   {
      this.borrowerName = borrowerName;
   }

   public Templating2DO(java.lang.Integer creditScore,
         java.lang.String creditStatus, java.lang.String borrowerName)
   {
      this.creditScore = creditScore;
      this.creditStatus = creditStatus;
      this.borrowerName = borrowerName;
   }

}